# Copyright (c) 2023-2025 David Bender <david@brickgraph.io>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Brickgraph | Academy
site_url: https://academy.brickgraph.io/
site_author: David Bender
site_description: Brickgraph - simple, powerful knowledge graphs for real world businesses

# Repository
#repo_name: Brickgraph/docs
#repo_url: https://github.com/Brickgraph/docs

# Copyright
copyright: Copyright &copy; 2023 - 2025 Brickgraph Incorporated
theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  language: en
  features:
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
extra:
  image_dir: img
extra_css:
  - extra.css
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://brickgraph.io
    - icon: fontawesome/brands/github
      link: https://github.com/Brickgraph
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/brickgraph
nav:
  - Brickgraph:
      - index.md
      - Getting Started: getting-started.md
      - Concepts:
          - concepts/index.md
          - Knowledge Graphs: concepts/knowledge-graphs/index.md
          - Maps & Geospatial: concepts/geospatial-analysis/index.md
          - Data Integration: concepts/data-integration/index.md
          - Permissions: concepts/permissions/index.md
          - LLMs: concepts/llms/index.md
          - Agents: concepts/agents/index.md
  - Features:
      - features/index.md
      - Graph: 
          - features/graph/index.md
          - Model Builder: features/graph/model-builder/index.md
          - Data: features/graph/data/index.md
      - Map: 
          - features/map/index.md
          - Styling: features/map/styling/index.md
          - Layers: features/map/layers/index.md
          - Layer Manager: features/map/manager/index.md
          - Screenshot: features/map/screenshots/index.md
      - Dashboard: features/dashboard/index.md
      - Reports: features/reports/index.md
      - Flows: features/flows/index.md
      - Assistant: features/assistant/index.md
      - API: features/api/index.md
      - Settings: features/settings/index.md
  - Guides:
      - guides/index.md
      - Quick Start: guides/sample-kg/index.md
      - Using Maps for Analysis: guides/map/index.md
      - Integrations:
          - guides/integrations/index.md
          - REST API: guides/integrations/api/index.md
          - Excel: guides/integrations/excel/index.md
          - Python: guides/integrations/python-api/index.md
      - Best Practices:
          - guides/best-practices/index.md
      - Advanced:
          - guides/advanced/index.md
  - Support: support.md
